In [4]:
import pandas as pd
meteor=pd.read_csv('/content/meteor/Meteorite_Landings.csv',nrows=5)
meteor

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21,Fell,1880,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720,Fell,1951,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000,Fell,1952,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914,Fell,1976,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780,Fell,1902,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [6]:
meteor.name

0      Aachen
1      Aarhus
2        Abee
3    Acapulco
4     Achiras
Name: name, dtype: object

In [7]:
meteor.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass (g)', 'fall', 'year',
       'reclat', 'reclong', 'GeoLocation'],
      dtype='object')

In [14]:
import requests
response=requests.get(
      'https://data.nasa.gov/resource/gh4g-9sfh.json',
      params={'$limit':50_000}
)
if response.ok:
  payload=response.json()
else:
  print(f'request was not successful and returned code:{response.status_code}.')
  payload=None

In [15]:
import pandas as pd
df=pd.DataFrame(payload)
df.head(3)

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation,:@computed_region_cbhk_fwbd,:@computed_region_nnqa_25f4
0,Aachen,1,Valid,L5,21,Fell,1880-01-01T00:00:00.000,50.775000,6.083330,"{'latitude': '50.775', 'longitude': '6.08333'}",NaN,NaN
1,Aarhus,2,Valid,H6,720,Fell,1951-01-01T00:00:00.000,56.183330,10.233330,"{'latitude': '56.18333', 'longitude': '10.23333'}",NaN,NaN
2,Abee,6,Valid,EH4,107000,Fell,1952-01-01T00:00:00.000,54.216670,-113.000000,"{'latitude': '54.21667', 'longitude': '-113.0'}",NaN,NaN

In [16]:
meteor.shape

(5, 10)

In [17]:
df.shape

(45716, 12)

In [18]:
meteor.dtypes
df.dtypes

name                           object
id                             object
nametype                       object
recclass                       object
mass                           object
fall                           object
year                           object
reclat                         object
reclong                        object
geolocation                    object
:@computed_region_cbhk_fwbd    object
:@computed_region_nnqa_25f4    object
dtype: object

In [19]:
meteor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         5 non-null      object
 1   id           5 non-null      int64
 2   nametype     5 non-null      object
 3   recclass     5 non-null      object
 4   mass (g)     5 non-null      int64
 5   fall         5 non-null      object
 6   year         5 non-null      int64
 7   reclat       5 non-null      float64
 8   reclong      5 non-null      float64
 9   GeoLocation  5 non-null      object
dtypes: float64(2), int64(3), object(5)
memory usage: 528.0+ bytes

In [22]:
meteor[['name', 'mass (g)']]

       name  mass (g)
0    Aachen        21
1    Aarhus       720
2      Abee    107000
3  Acapulco      1914
4   Achiras       780

In [25]:
meteor[4:9]

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
4,Achiras,370,Valid,L6,780,Fell,1902,-33.16667,-64.95,"(-33.16667, -64.95)"

In [26]:
meteor.iloc[4:9,[0,3,4,6]]

      name recclass  mass (g)  year
4  Achiras       L6       780  1902

In [27]:
meteor.loc[4:9,'mass (g)':'year']

   mass (g)  fall  year
4       780  Fell  1902

In [28]:
(meteor['mass (g)']>50)&(meteor.fall == 'Found')

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [30]:
(meteor['reclat']<50)&(meteor.fall == 'Found')

0    False
1    False
2    False
3    False
4    False
dtype: bool